# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0930507a213642800a27868c40b2b39edb1de11b21eca4e2d48627c68f83b33f8573b6c6574d9028cb00f4831f2a59614268cd099ec5044c5aca3f05ba0025f1

test:
  secret_key_base: 8f1af34879619fe104e1afe7bc09252bda21e8cb1c21ba5d0bc6c8e0713f410af56702a09253c2ea242af6bbdf4e4050ac5c23361959f9b32017dd1909fa6d73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
